version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
  development-deploy:
    machine:
      enabled: true
    steps:
  approval-job:

  production-deploy:
    machine:
      enabled: true
    steps:
workflows:
    build-and-test:
      jobs:
        - development-deploy:
            filters:
              branches:
                only: master
        - approval-job:
            type: approval
            requires:
              - development-deploy
            filters:
              branches:
                only: master
        - production-deploy:
            requires:
              - approval-job
            filters:
              branches:
                only: master
